name: stormy_streamer
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  intl: ^0.18.1
  json_annotation: ^4.8.1
  rxdart: ^0.27.7
  mockito: ^5.4.2
  mocktail: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

  http_mock_adapter: ^0.6.0

flutter:

  assets:
    - assets/
